

export const COLLECTION_OP_MINT = 1;
export const COLLECTION_OP_UPDATE_OWNER = 2;
export const COLLECTION_OP_UPDATE_CONTENT = 3;
export const COLLECTION_OP_UPDATE_ROYALTY = 4;
export const COLLECTION_OP_UPDATE_ITEM_CONTENT = 5;
export const COLLECTION_OP_SWITCH_ITEM_UPDATE_CONTENT = 6;

export const COLLECITON_OP_GET_ROYALTY_PARAMS = 0x693d3950;

export const ITEM_OP_UPDATE_CONTENT = 1;
export const ITEM_OP_SWITCH_UPDATE_CONTENT = 2;
export const ITEM_OP_GET_STATIC_DATA = 0x2fcb26a2;